from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_about_me(object):
    def setupUi(self, about_me):
        about_me.setObjectName("about_me")
        about_me.resize(1133, 862)
        self.centralwidget = QtWidgets.QWidget(about_me)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-1, -1, 1131, 841))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:15px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(640, 360, 471, 451))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../Pictures/Contact us-bro.svg"))
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 1131, 101))
        self.frame_2.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.close = QtWidgets.QPushButton(self.frame_2)
        self.close.setGeometry(QtCore.QRect(1090, 10, 31, 28))
        self.close.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.close.setStyleSheet("background-color: rgb(193, 0, 0);\n"
"border-radius:8px;\n"
"")
        self.close.setText("")
        self.close.setObjectName("close")
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setGeometry(QtCore.QRect(520, 0, 111, 101))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("../Pictures/icons8-youtube-512.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(80, 20, 111, 61))
        font = QtGui.QFont()
        font.setFamily("Raleway")
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(10, 20, 61, 61))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("../Pictures/icons8-info-480.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.max = QtWidgets.QPushButton(self.frame_2)
        self.max.setGeometry(QtCore.QRect(1050, 10, 31, 28))
        self.max.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.max.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"border-radius:8px;")
        self.max.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../YOUTUBE_DOWNLOADER/Pictures/icons8-subtract-90.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.max.setIcon(icon)
        self.max.setObjectName("max")
        self.min = QtWidgets.QPushButton(self.frame_2)
        self.min.setGeometry(QtCore.QRect(1010, 10, 31, 28))
        self.min.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.min.setStyleSheet("background-color: rgb(0, 229, 0);\n"
"border-radius:8px;")
        self.min.setText("")
        self.min.setIcon(icon)
        self.min.setObjectName("min")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(0, 89, 191, 751))
        self.frame_3.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.pushButton = QtWidgets.QPushButton(self.frame_3)
        self.pushButton.setGeometry(QtCore.QRect(0, 10, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Raleway SemiBold")
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setToolTip("")
        self.pushButton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 0, 0);\n"
"border-radius:0px;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Pictures/icons8-home-100 (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setIconSize(QtCore.QSize(50, 50))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 90, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Raleway SemiBold")
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setAcceptDrops(False)
        self.pushButton_2.setToolTip("")
        self.pushButton_2.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 0, 0);\n"
"border-radius:0px;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../Pictures/icons8-download-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_3.setGeometry(QtCore.QRect(0, 170, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Raleway SemiBold")
        font.setPointSize(14)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setToolTip("")
        self.pushButton_3.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 0, 0);\n"
"border-radius:0px;")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../Pictures/icons8-setting-256.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon3)
        self.pushButton_3.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_8 = QtWidgets.QLabel(self.frame_3)
        self.label_8.setGeometry(QtCore.QRect(0, 700, 191, 21))
        self.label_8.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_8.setText("")
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_12 = QtWidgets.QLabel(self.frame_3)
        self.label_12.setGeometry(QtCore.QRect(0, 670, 191, 21))
        self.label_12.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_12.setText("")
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frame_3)
        self.label_13.setGeometry(QtCore.QRect(0, 640, 191, 21))
        self.label_13.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_13.setText("")
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.frame_3)
        self.label_14.setGeometry(QtCore.QRect(0, 610, 191, 21))
        self.label_14.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_14.setText("")
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.frame_3)
        self.label_15.setGeometry(QtCore.QRect(0, 580, 191, 21))
        self.label_15.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_15.setText("")
        self.label_15.setScaledContents(True)
        self.label_15.setObjectName("label_15")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setGeometry(QtCore.QRect(200, 260, 461, 511))
        self.frame_4.setStyleSheet("background-color:rgb(255, 0, 0) ;\n"
"color:rgb(0, 0, 0);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame_4)
        self.textBrowser.setGeometry(QtCore.QRect(20, 160, 421, 111))
        font = QtGui.QFont()
        font.setFamily("Raleway SemiBold")
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.label_16 = QtWidgets.QLabel(self.frame_4)
        self.label_16.setGeometry(QtCore.QRect(0, 130, 461, 21))
        self.label_16.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_16.setText("")
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.frame_4)
        self.textBrowser_2.setGeometry(QtCore.QRect(20, 10, 421, 111))
        font = QtGui.QFont()
        font.setFamily("Raleway SemiBold")
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label_17 = QtWidgets.QLabel(self.frame_4)
        self.label_17.setGeometry(QtCore.QRect(0, 310, 461, 21))
        self.label_17.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_17.setText("")
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName("label_17")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.frame_4)
        self.textBrowser_3.setGeometry(QtCore.QRect(20, 340, 421, 51))
        font = QtGui.QFont()
        font.setFamily("Raleway SemiBold")
        self.textBrowser_3.setFont(font)
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setGeometry(QtCore.QRect(-1, 430, 461, 80))
        self.frame_5.setStyleSheet("background-color: rgb(159, 0, 0);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.github = QtWidgets.QPushButton(self.frame_5)
        self.github.setGeometry(QtCore.QRect(10, 10, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.github.setFont(font)
        self.github.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.github.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.github.setObjectName("github")
        self.email = QtWidgets.QPushButton(self.frame_5)
        self.email.setGeometry(QtCore.QRect(160, 10, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.email.setFont(font)
        self.email.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.email.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.email.setObjectName("email")
        self.social = QtWidgets.QPushButton(self.frame_5)
        self.social.setGeometry(QtCore.QRect(310, 10, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.social.setFont(font)
        self.social.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.social.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.social.setObjectName("social")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(290, 150, 721, 41))
        font = QtGui.QFont()
        font.setFamily("Raleway")
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_3.setObjectName("label_3")
        about_me.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(about_me)
        self.statusbar.setObjectName("statusbar")
        about_me.setStatusBar(self.statusbar)

        self.retranslateUi(about_me)
        self.close.clicked.connect(about_me.close)
        self.min.clicked.connect(about_me.showMinimized)
        self.max.clicked.connect(about_me.showNormal)
        QtCore.QMetaObject.connectSlotsByName(about_me)

    def retranslateUi(self, about_me):
        _translate = QtCore.QCoreApplication.translate
        about_me.setWindowTitle(_translate("about_me", "MainWindow"))
        self.close.setToolTip(_translate("about_me", "close"))
        self.label_10.setText(_translate("about_me", "About Me"))
        self.max.setToolTip(_translate("about_me", "normal"))
        self.min.setToolTip(_translate("about_me", "minimize"))
        self.pushButton.setText(_translate("about_me", "Home"))
        self.pushButton.setShortcut(_translate("about_me", "Home"))
        self.pushButton_2.setText(_translate("about_me", "Downloader"))
        self.pushButton_3.setText(_translate("about_me", "Profile"))
        self.textBrowser.setHtml(_translate("about_me", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Raleway SemiBold\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt;\">savify is a Youtube Video Downloader </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt;\">using savify you can download Youtube Videos with highest resolutions</span></p></body></html>"))
        self.textBrowser_2.setHtml(_translate("about_me", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Raleway SemiBold\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt;\">I\'m a Teenager who is highly interested in Computers and Programming.</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:14pt;\"><br /></p></body></html>"))
        self.textBrowser_3.setHtml(_translate("about_me", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Raleway SemiBold\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt;\">Also you can contact me via:</span></p></body></html>"))
        self.github.setText(_translate("about_me", "Github"))
        self.email.setText(_translate("about_me", "Email"))
        self.social.setText(_translate("about_me", "Social Media"))
        self.label_3.setText(_translate("about_me", "Savify is an easy-to-use Youtube Video Downloader "))

